# lighthouse-keeper.yml
name: Lighthouse Keeper
on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes`
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug logging'
        required: false
        default: 'false'
        type: boolean

jobs:
  searchlight:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Install mise and tools
      uses: jdx/mise-action@v2
      with:
        cache: true  # This caches the tools, not mise itself
        install: |
          nickel@latest
        # config-file: lighthouse/mise/config.toml

    - name: Restore state cache
      uses: actions/cache@v4
      with:
        path: lighthouse-state.json
        key: lighthouse-state-${{ github.run_id }}
        restore-keys: |
          lighthouse-state-
    
    - name: Check resources and trigger builds
      run: |
        # Read lighthouse.ncl config
        # Load lighthouse-state.json (or create if missing)
        # Check GitHub APIs for changes
        # Trigger workflows if needed
        # Update lighthouse-state.json
    
    - name: Save state cache
      uses: actions/cache/save@v4
      with:
        path: lighthouse-state.json
        key: lighthouse-state-${{ github.run_id }}